title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
title: Nicholas Huynh
description: Welcome to my portfolio!

links:
  linkedin: https://www.linkedin.com/in/nicholas-huynh111/
  resume: https://drive.google.com/file/d/1iCEH-xpObbmJeZoFpKRbXFoFdTX_lOZV/view?usp=sharing
  github:
    aquarium: https://github.com/nhuynh11/AquariumManager
    workout: https://github.com/nhuynh11/LinearProgramTracker
