title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
title: Nicholas Huynh
description: THIS PORTFOLIO SITE IS NO LONGER BEING USED. PLEASE VISIT NICHOLASHUYNH.COM

links:
  linkedin: https://www.linkedin.com/in/nicholas-huynh111/
  resume: https://drive.google.com/file/d/1KO3GUgS62BEktLYJWETz9OU94kHO3Z9x/view?usp=sharing
  github:
    aquarium: https://github.com/nhuynh11/AquariumManager
    workout: https://github.com/nhuynh11/LinearProgramTracker
  portfolio: https://www.nicholashuynh.com/
